default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: railsmeet_development
  username: postgres
  password: admin
  host: localhost

test:
  <<: *default
  database: railsmeet_test
  username: postgres
  password: admin

production:
  <<: *default
  database:  <%= ENV['DATABASE_URL'] %>